### ISSUE TITLE
Adding to the logseq marketplace

### ISSUE THREAD

**Issue by sawhney17** [gidongkwon/logseq-plugin-tags#1]
Amazing job on the plugin! Tried it and can definitely see this slotting into my workflow while also making it easier for those coming from Obsidian. 

One request though, I love having all my plugins in the marketplace so that i can easily update and would love if you could put this up there as well. 

Thanks again for the lovely plugin!

**Comment by gidongkwon** [comment]
Sure! I'm glad that you found value in this plugin.

**Comment by gidongkwon** [comment]
https://github.com/logseq/marketplace/pull/66
Merged!
