### ISSUE TITLE
Please add a sorting function，thank you very much

### ISSUE THREAD

**Issue by gujin03** [gidongkwon/logseq-plugin-tags#3]
This plugin is very useful to me.
Please add a sorting function order by desc in default, thank you.

**Comment by gidongkwon** [comment]
v0.1.0 have sorting functions, and they are saved, so you can use as it is after reopen window! Please let me know if insufficient.

**Comment by gujin03** [comment]
> v0.1.0 have sorting functions, and they are saved, so you can use as it is after reopen window! Please let me know if insufficient.

excellent
