### ISSUE TITLE
feature request: Dark mode UI

### ISSUE THREAD

**Issue by sawhney17** [gidongkwon/logseq-plugin-tags#4]
Feature request from twitter:
<img width="597" alt="Screen Shot 2022-01-04 at 10 26 41 AM" src="https://user-images.githubusercontent.com/80150109/148020140-ebf9434e-9e59-4f6d-ac13-44dc9589f6a8.png">

https://twitter.com/Riccardo_T/status/1478248112934330373

If you don't mind, I'd like to contribute a PR about this.

**Comment by gidongkwon** [comment]
Dark mode support added in v0.1.0!
